name: Ubuntu22.02

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v4
      # Step 2 - Runs the Ubuntu setup script
      - name: Test install
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./tests/ubuntu22.04/Dockerfile
          push: true
          tags: "chao123/ubuntu:latest"