name: Ubuntu22.02

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
      # Step 2 - Runs the Ubuntu setup script
      - name: Test install
        run: sudo sh ubuntu.sh
