name: Ubuntu22.02

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    environment:
      name: someip-docker

    steps:
      # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3 - Runs the Ubuntu setup script
      - name: Test install
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./tests/ubuntu22.04/Dockerfile
          push: false
          tags: "chao123/ubuntu:latest"